const $=s=>document.querySelector(s);let lastReply="";let stopped=false;let audioCtx=null;let audioUnlocked=false;
function msg(who,text,meta=""){const d=document.createElement("div");d.className="message "+(who==="YOU"?"user":"vesper");d.innerHTML="<b>"+who+"</b><p></p>"+(meta?"<span class=meta></span>":"");d.querySelector("p").textContent=text;if(meta)d.querySelector(".meta").textContent=meta;$("#messages").appendChild(d);$("#messages").scrollTop=$("#messages").scrollHeight}
async function health(){try{const r=await fetch("/api/health");const j=await r.json();$("#dio").textContent=j.ready?"READY":"UNAVAILABLE";$("#liveState").textContent=j.ready?"LIVE":"DEGRADED";$("#liveDot").style.color=j.ready?"#54f0c1":"#ff9f9f";$("#voiceState").textContent=(j.voice&&j.voice.ready)?"Vera Pocket · READY":"Vera Pocket · "+((j.voice&&j.voice.state)||"UNAVAILABLE")}catch(e){$("#dio").textContent="UNAVAILABLE";$("#liveState").textContent="OFFLINE"}}
function project(j){const d=j.decision||{},a=j.authority||{},i=j.intake||{};$("#decision").className="receipt";$("#decision").textContent=(d.intent||"unknown")+" → "+(d.product||"unresolved")+" · "+Math.round((d.confidence||0)*100)+"% · "+(d.source||"unknown");const review=i.authority&&i.authority.operator_review_required;$("#authority").className="receipt "+(review?"needs":"");$("#authority").innerHTML=(review?"HUMAN REVIEW · REQUIRED<br>":"")+"Spend · "+(a.spend_authorized?"AUTHORIZED":"LOCKED")+"<br>Fulfilment · "+(a.fulfilment_released?"RELEASED":"LOCKED")+"<br>External action · "+(a.executed_external_action?"EXECUTED":"LOCKED");$("#evidence").textContent=JSON.stringify(j,null,2)}
async function unlockAudio(){if(audioUnlocked)return true;try{const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx)return false;audioCtx=audioCtx||new Ctx();if(audioCtx.state==="suspended")await audioCtx.resume();const b=audioCtx.createBuffer(1,1,22050),s=audioCtx.createBufferSource();s.buffer=b;s.connect(audioCtx.destination);s.start(0);audioUnlocked=audioCtx.state==="running";if(audioUnlocked)$("#voiceState").textContent="Vera Pocket · audio armed";return audioUnlocked}catch(e){return false}}
async function playBlob(blob){if(audioCtx&&audioUnlocked){const data=await blob.arrayBuffer();const buffer=await audioCtx.decodeAudioData(data.slice(0));const source=audioCtx.createBufferSource();source.buffer=buffer;source.connect(audioCtx.destination);return new Promise((resolve,reject)=>{source.onended=resolve;try{source.start(0)}catch(e){reject(e)}})}const u=URL.createObjectURL(blob);const a=new Audio(u);return new Promise((resolve,reject)=>{a.onended=()=>{URL.revokeObjectURL(u);resolve()};a.onerror=()=>{URL.revokeObjectURL(u);reject(new Error("HTML audio playback failed"))};a.play().catch(reject)})}
async function speak(text){if(!text||stopped)return;$("#voiceState").textContent="Vera Pocket · rendering";try{const r=await fetch("/api/speak",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text})});if(!r.ok)throw Error(await r.text());const b=await r.blob();$("#voiceState").textContent="Vera Pocket · speaking";await playBlob(b);$("#voiceState").textContent="Vera Pocket · READY"}catch(e){$("#voiceState").textContent="Voice blocked · tap Speak last reply";console.warn("Vera playback:",e)}}
$("#composer").addEventListener("submit",async e=>{e.preventDefault();if(stopped)return;await unlockAudio();const text=$("#text").value.trim();if(!text)return;$("#text").value="";msg("YOU",text);try{const r=await fetch("/api/message",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text})});const j=await r.json();if(!r.ok)throw Error(j.detail||JSON.stringify(j));const reply=(j.reply&&j.reply.text)||"Vesper returned no text reply.";lastReply=reply;msg("VESPER",reply,(j.intake&&j.intake.intake_id)||"");project(j);await speak(reply)}catch(e){msg("SYSTEM","Request refused or unavailable: "+e.message)}});
$("#speakLast").onclick=async()=>{await unlockAudio();await speak(lastReply)};$("#stop").onclick=()=>{stopped=true;if(audioCtx)audioCtx.close().catch(()=>{});window.speechSynthesis&&speechSynthesis.cancel();$("#liveState").textContent="SAFE STOP";$("#text").disabled=true};
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(SR){const rec=new SR();rec.lang="en-ZA";rec.interimResults=false;$("#mic").onclick=async()=>{await unlockAudio();rec.start()};rec.onresult=e=>{$("#text").value=e.results[0][0].transcript;$("#composer").requestSubmit()};rec.onerror=()=>{$("#voiceState").textContent="Browser microphone unavailable"}}else{$("#mic").disabled=true;$("#mic").title="Speech recognition unavailable in this browser"}
health();