// Vesper reveals canonical DIO text only when Vera's first audio chunk is ready.
const $=s=>document.querySelector(s);let stopped=false;let audioCtx=null;let audioUnlocked=false;
function msg(who,text,meta=""){const d=document.createElement("div");d.className="message "+(who==="YOU"?"user":"vesper");d.innerHTML="<b>"+who+"</b><p></p>"+(meta?"<span class=meta></span>":"");d.querySelector("p").textContent=text;if(meta)d.querySelector(".meta").textContent=meta;$("#messages").appendChild(d);$("#messages").scrollTop=$("#messages").scrollHeight}
async function health(){try{const r=await fetch("/api/health");const j=await r.json();$("#dio").textContent=j.ready?"READY":"UNAVAILABLE";$("#liveState").textContent=j.ready?"LIVE":"DEGRADED";$("#liveDot").style.color=j.ready?"#54f0c1":"#ff9f9f";$("#voiceState").textContent=(j.voice&&j.voice.ready)?"Vera Pocket · READY":"Vera Pocket · "+((j.voice&&j.voice.state)||"UNAVAILABLE")}catch(e){$("#dio").textContent="UNAVAILABLE";$("#liveState").textContent="OFFLINE"}}
function project(j){const d=j.decision||{},a=j.authority||{},i=j.intake||{};$("#decision").className="receipt";$("#decision").textContent=(d.intent||"unknown")+" → "+(d.product||"unresolved")+" · "+Math.round((d.confidence||0)*100)+"% · "+(d.source||"unknown");const review=i.authority&&i.authority.operator_review_required;$("#authority").className="receipt "+(review?"needs":"");$("#authority").innerHTML=(review?"HUMAN REVIEW · REQUIRED<br>":"")+"Spend · "+(a.spend_authorized?"AUTHORIZED":"LOCKED")+"<br>Fulfilment · "+(a.fulfilment_released?"RELEASED":"LOCKED")+"<br>External action · "+(a.executed_external_action?"EXECUTED":"LOCKED");$("#evidence").textContent=JSON.stringify(j,null,2)}
async function unlockAudio(){if(audioUnlocked)return true;try{const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx)return false;audioCtx=audioCtx||new Ctx();if(audioCtx.state==="suspended")await audioCtx.resume();const b=audioCtx.createBuffer(1,1,22050),s=audioCtx.createBufferSource();s.buffer=b;s.connect(audioCtx.destination);s.start(0);audioUnlocked=audioCtx.state==="running";return audioUnlocked}catch(e){return false}}
function speechChunks(text){const clean=text.trim();if(!clean)return[];const sentences=clean.match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[clean];const chunks=[];for(const raw of sentences){const s=raw.trim();if(!s)continue;if(s.length<=125){chunks.push(s);continue}const parts=s.match(/.{1,105}(?:[,;:]|\s|$)/g)||[s];for(const p of parts){const q=p.trim();if(q)chunks.push(q)}}return chunks}
async function renderChunk(text){const r=await fetch("/api/speak",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text})});if(!r.ok)throw Error(await r.text());return r.blob()}
async function playBlob(blob){if(audioCtx&&audioUnlocked){const data=await blob.arrayBuffer(),buffer=await audioCtx.decodeAudioData(data.slice(0)),source=audioCtx.createBufferSource();source.buffer=buffer;source.connect(audioCtx.destination);return new Promise((resolve,reject)=>{source.onended=resolve;try{source.start(0)}catch(e){reject(e)}})}const u=URL.createObjectURL(blob),a=new Audio(u);return new Promise((resolve,reject)=>{a.onended=()=>{URL.revokeObjectURL(u);resolve()};a.onerror=()=>{URL.revokeObjectURL(u);reject(new Error("HTML audio playback failed"))};a.play().catch(reject)})}
async function prepareAndSpeak(text,onReady){if(!text||stopped)return;const chunks=speechChunks(text);if(!chunks.length){onReady();return}$("#voiceState").textContent="VESPER · preparing response…";try{let pending=renderChunk(chunks[0]);const first=await pending;if(stopped)return;onReady();$("#voiceState").textContent="Vera Pocket · speaking";if(chunks.length>1)pending=renderChunk(chunks[1]);await playBlob(first);for(let i=1;i<chunks.length&&!stopped;i++){const blob=await pending;if(i+1<chunks.length)pending=renderChunk(chunks[i+1]);await playBlob(blob)}$("#voiceState").textContent=stopped?"Vera Pocket · stopped":"Vera Pocket · READY"}catch(e){onReady();$("#voiceState").textContent="Vera Pocket · unavailable · text preserved";console.warn("Vera playback:",e)}}
$("#composer").addEventListener("submit",async e=>{e.preventDefault();if(stopped)return;await unlockAudio();const text=$("#text").value.trim();if(!text)return;$("#text").value="";msg("YOU",text);$("#voiceState").textContent="VESPER · resolving intent…";try{const r=await fetch("/api/message",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text})});const j=await r.json();if(!r.ok)throw Error(j.detail||JSON.stringify(j));const reply=(j.reply&&j.reply.text)||"Vesper returned no text reply.";project(j);let revealed=false;const reveal=()=>{if(revealed)return;revealed=true;msg("VESPER",reply,(j.intake&&j.intake.intake_id)||"")};await prepareAndSpeak(reply,reveal)}catch(e){$("#voiceState").textContent="Vera Pocket · READY";msg("SYSTEM","Request refused or unavailable: "+e.message)}});
$("#stop").onclick=()=>{stopped=true;if(audioCtx)audioCtx.close().catch(()=>{});window.speechSynthesis&&speechSynthesis.cancel();$("#liveState").textContent="SAFE STOP";$("#text").disabled=true};
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(SR){const rec=new SR();rec.lang="en-ZA";rec.interimResults=false;$("#mic").onclick=async()=>{await unlockAudio();rec.start()};rec.onresult=e=>{$("#text").value=e.results[0][0].transcript;$("#composer").requestSubmit()};rec.onerror=()=>{$("#voiceState").textContent="Browser microphone unavailable"}}else{$("#mic").disabled=true;$("#mic").title="Speech recognition unavailable in this browser"}
health();